name: Python Tests

on:
  push:
    branches:
      - main  # Change to the name of your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0  # Choose the Python version you need

    - name: Install dependencies
      run: |
        pip install pytest 
        pip install selenium webdriver_manager
        pip install pytest-cov coverage
        
        

    - name: Run tests
      run: 
         python test_main.py --cov=./ --cov-report=xml
         coverage run -m pytest test_main.py
         coverage report


    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
